"""
WebSocket endpoint with Redis pub/sub subscription for real-time summary delivery.

When a user connects via WebSocket we:
1. Validate the JWT access token (same flow as HTTP endpoints).
2. Register the socket with the in-process ConnectionManager so task mutations
   can be broadcast immediately from API handlers.
3. Subscribe to the Redis pub/sub channel ``summary:{user_id}`` in a background
   asyncio task so day-end summaries generated by Celery workers are forwarded
   to the browser tab in real time without polling.
"""
import asyncio
import json

import redis.asyncio as aioredis
from fastapi import APIRouter, WebSocket, WebSocketDisconnect, Query, status
from sqlalchemy import select

from app.config import settings
from app.core.security import decode_token
from app.database import AsyncSessionLocal
from app.models import User
from app.websocket.connection_manager import manager

router = APIRouter(tags=["websocket"])


async def _forward_redis_to_ws(user_id, websocket: WebSocket) -> None:
    """Subscribe to the user's Redis summary channel and forward messages to the WS.

    Runs as a concurrent asyncio task alongside the main receive loop.
    Exits cleanly when the WebSocket closes or on any Redis error.
    """
    redis_client: aioredis.Redis = aioredis.from_url(settings.REDIS_URL, decode_responses=True)
    pubsub = redis_client.pubsub()
    channel = f"summary:{user_id}"
    try:
        await pubsub.subscribe(channel)
        async for raw in pubsub.listen():
            if raw["type"] != "message":
                continue
            try:
                msg = json.loads(raw["data"])
            except (json.JSONDecodeError, TypeError):
                continue
            try:
                await websocket.send_json(msg)
            except Exception:
                # WebSocket already closed — stop listening.
                break
    except asyncio.CancelledError:
        pass
    except Exception:
        pass
    finally:
        try:
            await pubsub.unsubscribe(channel)
            await redis_client.aclose()
        except Exception:
            pass


@router.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket, token: str = Query(...)):
    # --- Auth ---
    try:
        payload = decode_token(token)
        if payload.get("type") != "access":
            raise ValueError
        from uuid import UUID
        user_id = UUID(payload["sub"])
    except (ValueError, KeyError, TypeError):
        await websocket.close(code=status.WS_1008_POLICY_VIOLATION)
        return

    async with AsyncSessionLocal() as db:
        result = await db.execute(select(User).where(User.id == user_id))
        if result.scalar_one_or_none() is None:
            await websocket.close(code=status.WS_1008_POLICY_VIOLATION)
            return

    # --- Connect to in-process manager + Redis subscriber ---
    await manager.connect(user_id, websocket)
    redis_task = asyncio.create_task(_forward_redis_to_ws(user_id, websocket))

    try:
        while True:
            data = await websocket.receive_json()
            # Clients may send lightweight pings; relay any task mutation
            # notices to this user's other connections.
            await manager.broadcast_to_user(user_id, data, exclude=websocket)
    except WebSocketDisconnect:
        pass
    finally:
        redis_task.cancel()
        manager.disconnect(user_id, websocket)
