"""Add daily_summaries table

Revision ID: 3a411409b853
Revises: 4b7ec721f457
Create Date: 2026-07-20 12:38:25.953452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a411409b853'
down_revision: Union[str, None] = '4b7ec721f457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_summary_user_date')
    )
    op.create_index('ix_daily_summaries_user_date_desc', 'daily_summaries', ['user_id', 'date'], unique=False, postgresql_ops={'date': 'DESC'})
    op.create_index(op.f('ix_hourly_checkin_reminders_response_id'), 'hourly_checkin_reminders', ['response_id'], unique=False)
    op.alter_column('reminder_activities', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint('fk_user_primary_device', 'users', type_='foreignkey')
    op.create_foreign_key('fk_user_primary_device', 'users', 'devices', ['primary_device_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_primary_device', 'users', type_='foreignkey')
    op.create_foreign_key('fk_user_primary_device', 'users', 'devices', ['primary_device_id'], ['id'], ondelete='SET NULL')
    op.alter_column('reminder_activities', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_hourly_checkin_reminders_response_id'), table_name='hourly_checkin_reminders')
    op.drop_index('ix_daily_summaries_user_date_desc', table_name='daily_summaries', postgresql_ops={'date': 'DESC'})
    op.drop_table('daily_summaries')
    # ### end Alembic commands ###
